from __future__ import annotations

"""
Pack the multi-module GA solution into a single-file submission for CodinGame.

Output: dist/submission_ga.py

Usage:
  python pack_submission.py

What it does:
- Concatenates terrain.py, physics.py, evaluation.py, ga.py, controller.py (in that order)
- Keeps only a single from __future__ import annotations at the very top
- Strips intra-project imports between these modules to avoid duplication
- Inserts clear section headers for readability

After packing, you can submit dist/submission_ga.py to CodinGame.
"""

import io
import os
from pathlib import Path
from typing import List

HERE = Path(__file__).resolve().parent
SRC_FILES = [
    "terrain.py",
    "physics.py",
    "evaluation.py",
    "ga.py",
    "controller.py",
]
OUTPUT_DIR = HERE / "dist"
OUTPUT_FILE = OUTPUT_DIR / "submission_ga.py"


STRIP_IMPORT_PREFIXES = (
    "from terrain import",
    "import terrain",
    "from physics import",
    "import physics",
    "from evaluation import",
    "import evaluation",
    "from ga import",
    "import ga",
)


def _should_strip(line: str) -> bool:
    s = line.strip()
    if not s:
        return False
    if s.startswith(STRIP_IMPORT_PREFIXES):
        return True
    return False


def pack() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    out = io.StringIO()
    wrote_future = False

    # Header
    out.write("# Submission generated by pack_submission.py\n")
    out.write("# Contains: terrain, physics, evaluation, ga, controller\n\n")

    for name in SRC_FILES:
        path = HERE / name
        if not path.exists():
            raise FileNotFoundError(f"Missing required source file: {path}")
        out.write(f"\n# ======== BEGIN {name} ========\n")
        with path.open("r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("from __future__ import annotations"):
                    if not wrote_future:
                        out.write("from __future__ import annotations\n")
                        wrote_future = True
                    # skip duplicates
                    continue
                if _should_strip(line):
                    continue
                out.write(line)
        out.write(f"\n# ======== END {name} ========\n")

    with OUTPUT_FILE.open("w", encoding="utf-8", newline="\n") as g:
        g.write(out.getvalue())

    print(f"Wrote single-file submission to: {OUTPUT_FILE}")


if __name__ == "__main__":
    pack()
